JobPortal/Job/urls.py
from django.urls import path
from . views import AcceptedApplicationsCountView, AcceptedApplicationsView, AppliedJobSeekersListView, CreateJobPostView,AddEducationView, DashboardView, DashboardView11, JobAppliListview, JobApplicationCountView, JobPostCountRecivedView, JobPostCountView, JobseekerReportsView, PendingApplicationsCountView, PendingApplicationsView, RecentAppliedJobsListView, RejectedApplicationsCountView, RejectedApplicationsView, ReportsView, ReportsstatusView, SearchAppliedJobs, SearchManageView, SearchStatusListview, SekkerSearchAllJobsView
from .import views

urlpatterns = [
    path('create_job_post/', CreateJobPostView.as_view(), name='create_job_post'),
    path('add_education', AddEducationView.as_view(),name="add_education"),
    path('add_salary_range/', views.AddSalaryView.as_view(), name='add_salary_range'),
    path('add_skill/', views.AddSkillView.as_view(), name='add_skill'),

    path('update_job_post/<int:id>/',views.UpdateJobView.as_view(),name="update_job_post"),
    path('job_details/<int:id>/',views.JobDetailsView.as_view(),name="job_details"),
    path('manage_jobs/',views.ManageJobsView.as_view(),name="manage_jobs"),
    path('seeker_view_all_jobs',views.AllJobSeekerView.as_view(),name="seeker_view_all_jobs"),
    path('update_jobs/<int:pk>/',views.UpdateJobPostView.as_view(),name="update_jobs"),
    path('delete_job/<int:pk>/',views.DeleteJobView.as_view(),name="delete_job"),
    path('search_results',views.SearchAllJobsView.as_view(),name="search_results"),#All job se4rach
    path('job_application_list_stat',views.JobApplicationListView.as_view(),name="job_application_list_stat"),
    path('search_results_managejobs',views.SearchResultManagejobsView.as_view(),name="search_results_managejobs"),
    path('search_results_applica',views.SearchResultApplicationView.as_view(),name="search_results_applica"),
    path('applied_job',views.AppliedJobView.as_view(),name="applied_job"),
    # path('jobPapplyseeker/<int:pk>/',views.JobApplyView.as_view(),name="jobPapplyseeker"),
    path('job_apply_seeker/<int:id>/',views.JobApplyView.as_view(),name="job_apply_seeker"),
    path('seeker_viewmore/<int:id>/',views.SeekViewMoreView.as_view(),name="seeker_viewmore"),
    path('job_application/<int:id>/',views.JobApplicationView.as_view(),name="job_application"),
    # path('job_application/<int:id>/',views.job_application,name="job_application"),
    path('status_track_seeker',views.StatusTarckSeekerView.as_view(),name="status_track_seeker"),
    # path('job_application_list_stat',views.JobApplicationListStatView.as_view(),name="job_application_list_stat"),
    path('status_track_update_emp/<int:pk>/',views.StatusTrackUpdateEmpView.as_view(),name="status_track_update_emp"),
    path('job_application_list_stats',views.JobApplicationListStatView.as_view(),name="job_application_list_stats"),
    path('all_applications/<int:id>/',views.AllApplicationsView.as_view(),name="all_applications"),
    path('download_resume/<int:file>/', views.DownloadResumeView.as_view(), name='download_resume'),
    path('search_results_resume_down',views.SearchResultsResumeDownloadView.as_view(),name="search_results_resume_down"),


    # path('count_total_application',views.JobPostCountsView.as_view(),name="count_total_application"),
    # path('count_total_application1',views.AllJobsCountView.as_view(),name="count_total_application1"),
  
    path('total_jobs/', JobApplicationCountView.as_view(), name='total_jobs'),
    path('applied_job_user/', JobAppliListview.as_view(), name='applied_job_user'),
    path('accepted_job_user/', AcceptedApplicationsView.as_view(), name='accepted_job_user'),
    path('rejected_job_user/', RejectedApplicationsView.as_view(), name='rejected_job_user'),
    path('pending_job_user/', PendingApplicationsView.as_view(), name='pending_job_user'),
    path('reports/', ReportsView.as_view(), name='reports'),
    path('reports_job/', JobseekerReportsView.as_view(), name='reports_job'),
    path('recent_applied_jobs/', RecentAppliedJobsListView.as_view(), name='recent_applied_jobs'),   
    path('count_total_post/',JobPostCountView.as_view(),name="count_total_post"),
    path('dashboard/',DashboardView.as_view(),name="dashboard"),
    path('dashboard1/',DashboardView11.as_view(),name="dashboard1"),
    path('count_total_applied/',JobPostCountRecivedView.as_view(),name="count_total_applied"),
    path('count_total/',AcceptedApplicationsCountView.as_view(),name="count_total"),
    path('count_rejected/',RejectedApplicationsCountView.as_view(),name="count_rejected"),
    path('count_pending/',PendingApplicationsCountView.as_view(),name="count_pending"),
    path('report_view/',ReportsstatusView.as_view(),name="report_view"),
    path('recent_apply/',AppliedJobSeekersListView.as_view(),name="recent_apply"),
    path('search_result/',SearchStatusListview.as_view(),name="search_result"),
    path('search_all_job/',SekkerSearchAllJobsView.as_view(),name="search_all_job"),
    path('applied_job_see/',SearchAppliedJobs.as_view(),name="applied_job_see"),
    path('search_manage/',SearchManageView.as_view(),name="search_manage"),
    # path('applied_job_see/',SearchAppliedJobs.as_view(),name="applied_job_see"),
    # path('applied_job_see/',SearchAppliedJobs.as_view(),name="applied_job_see"),
    # path('applied_job_see/',SearchAppliedJobs.as_view(),name="applied_job_see"),
    # path('applied_job_see/',SearchAppliedJobs.as_view(),name="applied_job_see"),
  




    # path('seeker_viewmore/<int:id>/',views.seeker_viewmore,name="seeker_viewmore"),
    # path('applied_job',views.applied_job,name="applied_job"),
    # path('jobPapplyseeker/<int:id>/',views.jobPapplyseeker,name="jobPapplyseeker"),
    # path('job_application/<int:id>/',views.job_application,name="job_application"),
    # path('all_applications/<int:id>/',views.all_applications,name="all_applications"),
    # path('download_resume/<int:file>/', views.download_resume, name='download_resume'),
    # path('search_results_resume_down',views.search_results_resume_down,name="search_results_resume_down"),
    # path('job_application_list_stat',views.job_application_list_stat,name="job_application_list_stat"),

    # path('create_job_post',views.create_job_post,name="create_job_post"),
    # path('update_job_post/<int:id>/',views.update_job_post,name="update_job_post"),
    # path('job_details/<int:id>/',views.job_details,name="job_details"),

    # #seeker view all active jobs
    # path('seeker_view_all_jobs',views.seeker_view_all_jobs,name="seeker_view_all_jobs"),
    # path('seeker_viewmore/<int:id>/',views.seeker_viewmore,name="seeker_viewmore"),
    # #seeker view all applied  jobs
    # path('applied_job',views.applied_job,name="applied_job"),

    # path('jobPapplyseeker/<int:id>/',views.jobPapplyseeker,name="jobPapplyseeker"),
    # path('job_application/<int:id>/',views.job_application,name="job_application"),
    # path('update_jobs/<int:id>/',views.update_jobs,name="update_jobs"),
    


    #search jobs seeker
    # path('search_results',views.search_results,name="search_results"),
    #search applica view  employer
    # path('search_results_applica',views.search_results_applica,name="search_results_applica"),
    # path('status_track_seeker',views.status_track_seeker,name="status_track_seeker"),
    # path('job_application_list_stats',views.job_application_list_stats,name="job_application_list_stats"),
    # path('status_track_update_emp/<int:id>/',views.status_track_update_emp,name="status_track_update_emp"),


#employer manage jobs and job seeker
    # path('manage_jobs',views.manage_jobs,name="manage_jobs"),
    # path('delete_job/<int:id>/',views.delete_job,name="delete_job"),
    # path('all_applications/<int:id>/',views.all_applications,name="all_applications"),
    # path('download_resume/<int:file>/', views.download_resume, name='download_resume'),
    # path('search_results_resume_down',views.search_results_resume_down,name="search_results_resume_down"),
    # path('search_results_managejobs',views.search_results_managejobs,name="search_results_managejobs"),
    # path('job_application_list_stat',views.job_application_list_stat,name="job_application_list_stat"),


    
]

JobPortal/JobPortal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/',include('Company.urls')),
    path('dashboard/',include('Dashboard.urls')),
    path('resume/',include('Resume.urls')),
    path('',include('UserApplicant.urls')),
    path('job/',include('Job.urls')),
  
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

JobPortal/Job/models.py
from django.db import models
from UserApplicant.models import User
from Company.models import Company
from Resume.models import Resume


class Skills_job(models.Model):
    name = models.CharField(max_length=255, blank=True,null=True)

    def __str__(self):
        return self.name

class Education(models.Model):
    name = models.CharField(max_length=255,blank=True,null=True)

    def __str__(self):
        return self.name
    
class SalaryRange(models.Model):
    salary_range = models.CharField(max_length=100)  

    def __str__(self):
        return self.salary_range

class JobPost(models.Model):
    # SALARY_CHOICES = [
    #     ('5,000-10,000' ,'5,000-10,000'),
    #     ('10,000-15,000','10,000-15,000'),
    #     ('15,000-20,000','15,000-20,000'),
    #     ('20,000-25,000','20,000-25,000'),
    #     ('25,000-30,000','25,000-30,000'),
    #     ('30,000-35,000','30,000-35,000'),
    #     ('35,000-40,000','35,000-40,000'),
    #     ('40,000-45,000','40,000-45,000'),
    #     ('45,000-50,000','45,000-50,000'),
    #     ('50,000+','50,000+'),
    # ]

    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-3', '1-3 years'),
        ('3-5', '3-5 years'),
        ('5-10', '5-10 years'),
        ('10+', '10+ years'),
    ]

    JOB_TYPE_CHOICES = [
        ('Full-Time', 'Full-Time'),
        ('Part-Time', 'Part-Time'),
        ('Internship', 'Internship'),
    ]

    user=models.ForeignKey(User, on_delete=models.CASCADE)
    company=models.ForeignKey(Company,on_delete=models.CASCADE,default='Select Your Company')
    skills = models.ManyToManyField(Skills_job, blank=True)
    title=models.CharField(max_length=255,blank=True, null=True)
    education=models.ForeignKey(Education,on_delete=models.CASCADE, default='Highest Qualification')
    salary=models.ForeignKey(SalaryRange,on_delete=models.CASCADE, default='10000-20000')
    overview =models.TextField(max_length=255,blank=True,null=True)
    location=models.CharField(max_length=255,blank=True,null=True)
    job_type =models.CharField(max_length=10,choices=JOB_TYPE_CHOICES,null=True, default='Full-Time')
    experience= models.CharField(max_length=5,choices=EXPERIENCE_CHOICES,null=True)
    # salary =models.CharField(max_length=25,choices=SALARY_CHOICES,default='50+',verbose_name='Salary Range')
    is_active= models.BooleanField(default=False)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
         return f"{self.title} - {self.company.name}"
    

class Apply_Job(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected'),
    ]

    user=models.ForeignKey(User,on_delete=models.CASCADE)
    job=models.ForeignKey(JobPost,on_delete=models.CASCADE) 
    timestamp=models.DateTimeField(auto_now_add=True)
    status= models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')

    def __str__(self):
        return f"{self.user.username}-{self.job.title}-{self.status}"

JobPortal/Job/forms.py
from django import forms
from .models import JobPost,Education,Skills_job,Apply_Job,SalaryRange
from Company.models import Company

# class JobPostForm(forms.ModelForm):
#     class Meta:
#         model=JobPost
#         exclude=('user',)
#         widgets = {
#                     'skills': forms.CheckboxSelectMultiple,
#                 }
class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['name']

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skills_job
        fields = ['name']
class SalaryRangeForm(forms.ModelForm):
    class Meta:
        model = SalaryRange
        fields = ['salary_range']

class JobPostForm(forms.ModelForm):
    class Meta:
        model = JobPost
        exclude = ('user',)
       
        widgets = {
            'skills': forms.CheckboxSelectMultiple,
        }
    education_form = EducationForm()
    salary_form = SalaryRangeForm()

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if user.is_authenticated and user.is_employer:
            self.fields['company'].queryset = Company.objects.filter(user=user)
        else:
            self.fields['company'].queryset = Company.objects.none()

    
       
   
       

class UpdateJobPostForm(forms.ModelForm):
    class Meta:
        model=JobPost
        exclude=('user',)

  
# class ApplyJobForm(forms.ModelForm):
#     cover_letter = forms.FileField(label='Upload cover letter', required=False)
#     resume = forms.FileField(label='Upload Resume', required=False)

#     class Meta:
#         model = Apply_Job
#         fields = ['resume', 'cover_letter']


class ApplyJobForm(forms.ModelForm):

    class Meta:
        model = Apply_Job
        fields = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = kwargs.pop('user', None)  
     

JobPortal/templates/Job/Job_post_list.html
<div id="search-results">
    {% for job in jobs %}
    <div class="job-details">
        <h2 style=" color: black; font-size: 40px;">{{ job.title }}</h2>
        <p><strong>Company:</strong> {{ job.company.name }}</p>
        <p><strong>Location:</strong> {{ job.location }}</p>
        <p><strong>Skills:</strong>
            {% for skill in job.skills.all %}
            {{ skill.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
        </p>
        <p><strong>Education:</strong> {{ job.education }}</p>
        <p><strong>Active:</strong> {{ job.timestamp|naturaltime }}</p>
        <a href="{% url 'seeker_viewmore' id=job.id %}" class="apply-now">View More</a>
    </div>
    {% endfor %}
</div>

JobPortal/templates/Job/Manage_search.html
    <tbody id="job-table-body">
        <tr>
            <th>Job title</th>
            <th>Location</th>
            <th>Salary</th>
            <th>No. of applicants</th>
            <th>Status</th>
            <th>Action</th>
            <th>Remove</th>
        </tr>
        {% for job in jobs %}
        <tr>
            <td data-th="Job title">{{ job.title }}</td>
            <td data-th="Location">{{ job.location }}</td>
            <td data-th="Salary">${{ job.salary }}</td>
            <td data-th="No. of applicants">
                {{ job.apply_job_set.count }} <a href="{% url 'all_applications' id=job.id %}" class="apply-now">Check List</a>
            </td>
            <td data-th="Status">
                {% if job.is_active %}
                <button style="color: #ffffff; background-color: #28a745; border-color: #28a745;" class="btn btn-sm btn-success">Active</button>
                {% else %}
                <button style="color: #ffffff; background-color: #dc3545; border-color: #dc3545;" class="btn btn-sm btn-danger">Inactive</button>
                {% endif %}
            </td>
            <td data-th="Action">
                <a href="{% url 'update_jobs' job.id %}" class="btn btn-sm btn-primary">Update</a>
            </td>
            <td data-th="Action">
                <a href="{% url 'delete_job' job.id %}" class="btn btn-sm btn-danger">Remove</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7" style="text-align: center;">No jobs found</td>
        </tr>
        {% endfor %}
    </tbody>






    

JobPortal/templates/Job/search_all_job.html
{% load humanize %}
{% for job in object_list %}
<div class="job-details">
    <h2 style="color: black; font-size: 40px; font-weight:bold;">{{ job.title }}</h2>
    <p><strong>Company:</strong> {{ job.company.name }}</p>
    <p><strong>Location:</strong> {{ job.location }}</p>
    <div class='job-info-row'>
        <div class="button-field">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-rupee" viewBox="0 0 16 16">
                <path d="M4 3.06h2.726c1.22 0 2.12.575 2.325 1.724H4v1.051h5.051C8.855 7.001 8 7.558 6.788 7.558H4v1.317L8.437 14h2.11L6.095 8.884h.855c2.316-.018 3.465-1.476 3.688-3.049H12V4.784h-1.345c-.08-.778-.357-1.335-.793-1.732H12V2H4z"/>
            </svg>
            <strong>{{ job.salary }} a month</strong>
        </div>
        <div class="button-field1">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
                <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71z"/>
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0"/>
            </svg>
            <strong>{{ job.job_type }}</strong>
        </div>
    </div>
    <p><strong>Active:</strong> {{ job.timestamp|naturaltime }}</p>
    <a href="{% url 'seeker_viewmore' id=job.id %}" class="apply-now">Easily Apply</a>
</div>
{% empty %}
<p>No results found.</p>
{% endfor %}

JobPortal/templates/Job/search_manage_job.html
{% for job in jobs %}
<tr>
    <td>{{ job.title }}</td>
    <td>{{ job.location }}</td>
    <td>{{ job.salary }}</td>
    <td>{{ job.apply_job_set.all.count }}</td>
    <td>
        {% if job.is_active %}
        <button style="color: #ebdcdc; background-color: green;">Active</button>
        {% else %}
        <button style="color: #fff; background-color: #ff0606;">Inactive</button>
        {% endif %}
    </td>
    <td>
        <a href="{% url 'update_jobs' job.id %}" class="btn btn-primary">Update</a>
    </td>
    <td>
        <a href="{% url 'delete_job' job.id %}" class="btn btn-sm btn-danger">Remove</a>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7">No jobs found.</td>
</tr>
{% endfor %}

JobPortal/templates/Job/search_status.html
<table class="rwd-table">
    <tbody id="job-table-body">
        <tr>
            <th>Job title</th>
            <th>User</th>
            <th>Status</th>
            <th>Date</th>
        </tr>
        {% if jobs %}
        {% for job in jobs %}
        <tr>
            <td data-th="Job title">{{ job.job.title }}</td>
            <td data-th="Location">
                {{ job.user.jobseeker_profile.first_name }} {{ job.user.jobseeker_profile.last_name }}
            </td>
            <td data-th="Status">
                {% if job.status == 'Pending' %}
                <a href="{% url 'status_track_update_emp' job.id %}" class="btn btn-primary">{{ job.status }}</a>
                {% elif job.status == 'Accepted' %}
                <a href="{% url 'status_track_update_emp' job.id %}" class="btn btn-success">{{ job.status }}</a>
                {% else %}
                <a href="{% url 'status_track_update_emp' job.id %}" class="btn btn-danger">{{ job.status }}</a>
                {% endif %}
            </td>
            <td data-th="Date">{{ job.timestamp|date:"Y-m-d" }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4" style="text-align: center;">No applications found</td>
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
</table>